<a href="https://colab.research.google.com/github/elijahmflomo/Sem_2_ADVANCED-REINFORCEMENT-LEARNING/blob/main/ARL_LAB_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Scenario 1:**

In [2]:
# Value Iteration Code

import numpy as np

gamma = 0.9
grid_size = 3
reward_step = -1
reward_goal = 10
goal = (2, 2)

V = np.zeros((grid_size, grid_size))

actions = [(-1,0), (1,0), (0,-1), (0,1)]  # Up, Down, Left, Right

def is_valid(x, y):
    return 0 <= x < grid_size and 0 <= y < grid_size

# Value Iteration (3 iterations)
for iteration in range(3):
    new_V = V.copy()
    for i in range(grid_size):
        for j in range(grid_size):
            if (i, j) == goal:
                new_V[i][j] = reward_goal
                continue

            values = []
            for dx, dy in actions:
                ni, nj = i + dx, j + dy
                if not is_valid(ni, nj):
                    ni, nj = i, j
                values.append(reward_step + gamma * V[ni][nj])

            new_V[i][j] = max(values)

    V = new_V
    print(f"After iteration {iteration + 1}:\n{V}\n")

print("Final Value Function:")
print(V)


After iteration 1:
[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. 10.]]

After iteration 2:
[[-1.9 -1.9 -1.9]
 [-1.9 -1.9  8. ]
 [-1.9  8.  10. ]]

After iteration 3:
[[-2.71 -2.71  6.2 ]
 [-2.71  6.2   8.  ]
 [ 6.2   8.   10.  ]]

Final Value Function:
[[-2.71 -2.71  6.2 ]
 [-2.71  6.2   8.  ]
 [ 6.2   8.   10.  ]]


In [3]:
# Policy Extraction Code

policy = np.full((grid_size, grid_size), '', dtype=object)
directions = ['↑', '↓', '←', '→']

for i in range(grid_size):
    for j in range(grid_size):
        if (i, j) == goal:
            policy[i][j] = 'G'
            continue

        best_value = -np.inf
        best_action = None

        for (dx, dy), d in zip(actions, directions):
            ni, nj = i + dx, j + dy
            if not is_valid(ni, nj):
                ni, nj = i, j
            value = reward_step + gamma * V[ni][nj]
            if value > best_value:
                best_value = value
                best_action = d

        policy[i][j] = best_action

print("Optimal Policy:")
print(policy)


Optimal Policy:
[['↑' '↓' '↓']
 ['↓' '↓' '↓']
 ['→' '→' 'G']]


Scenario 2

In [4]:
# Value Iteration Code

gamma = 0.95

# State values
V_S1 = 0
V_S2 = 10  # terminal state

# Value Iteration loop
for i in range(10):
    Q_study = -2 + gamma * (0.8 * V_S2 + 0.2 * V_S1)
    Q_relax = -1 + gamma * V_S1
    V_S1 = max(Q_study, Q_relax)

print("Value of S1:", V_S1)
print("Value of S2:", V_S2)


Value of S1: 6.913579823037395
Value of S2: 10


Optimal Policy Determination

In [5]:
Q_study = -2 + gamma * (0.8 * V_S2 + 0.2 * V_S1)
Q_relax = -1 + gamma * V_S1

if Q_study > Q_relax:
    print("Optimal Action in S1: Study")
else:
    print("Optimal Action in S1: Relax")


Optimal Action in S1: Study


Policy Iteration (Policy Improvement Step)

In [6]:
# Initial policy
policy = "Relax"

# Policy Improvement
if Q_study > Q_relax:
    policy = "Study"

print("Improved Policy:", policy)


Improved Policy: Study


Scenario 3

In [7]:
# Value Iteration

gamma = 0.8

# Initialize values
V_W = 0
V_T = 0
V_D = 0  # terminal

# Iteration 1
V_T = max(0.7 * 5 + gamma * V_D, -2 + gamma * V_W)
V_W = -1 + gamma * V_T

print("After Iteration 1")
print("V(W):", V_W)
print("V(T):", V_T)
print("V(D):", V_D)

# Iteration 2
V_T = max(0.7 * 5 + gamma * V_D, -2 + gamma * V_W)
V_W = -1 + gamma * V_T

print("\nAfter Iteration 2")
print("V(W):", V_W)
print("V(T):", V_T)
print("V(D):", V_D)


After Iteration 1
V(W): 1.8000000000000003
V(T): 3.5
V(D): 0

After Iteration 2
V(W): 1.8000000000000003
V(T): 3.5
V(D): 0


In [8]:
# Optimal Policy Extraction

Q_T_continue = 0.7 * 5 + gamma * V_D
Q_T_return = -2 + gamma * V_W

if Q_T_continue > Q_T_return:
    action_T = "Continue"
else:
    action_T = "Return"

print("\nOptimal Policy:")
print("State W → Fly")
print("State T →", action_T)
print("State D → Terminal")



Optimal Policy:
State W → Fly
State T → Continue
State D → Terminal


In [9]:
# Policy Iteration (Policy Improvement Step)

policy_T = "Return"  # initial random policy

if Q_T_continue > Q_T_return:
    policy_T = "Continue"

print("\nImproved Policy at T:", policy_T)



Improved Policy at T: Continue


Scenario 4

In [10]:
# Value Iteration Code

gamma = 0.85

# Initial values
V_G = 0
V_B = 0  # terminal

# Value Iteration loop
for i in range(10):
    Q_maintain = -2 + gamma * (0.9 * V_G)
    Q_ignore = 1 + gamma * (0.6 * V_G)
    V_G = max(Q_maintain, Q_ignore)

print("Value of State G:", V_G)


Value of State G: 2.03838688930964


In [11]:
# Optimal Policy Determination


Q_maintain = -2 + gamma * (0.9 * V_G)
Q_ignore = 1 + gamma * (0.6 * V_G)

if Q_ignore > Q_maintain:
    print("Optimal Policy: Ignore")
else:
    print("Optimal Policy: Maintain")


Optimal Policy: Ignore


In [12]:
# Policy Iteration (Policy Improvement Step)

# Initial policy
policy = "Maintain"

# Policy improvement
if Q_ignore > Q_maintain:
    policy = "Ignore"

print("Improved Policy:", policy)


Improved Policy: Ignore
